services:
  frontend:
    image: tajievolimjon/admin_sarez_web
    container_name: admin_sarez_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    extra_hosts:
      - "admin.sarezmobile.com:127.0.0.1"
