# services:
#   frontend:
#     build: .
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     command: ["npm", "run", "dev", "--", "--host"]

services:
  frontend:
    image: tajievolimjon/admin_sarez_web
    container_name: admin_sarez_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped